wso2/streaming-integrator-tooling

modules/distribution/carbon-home/conf/server/deployment.yaml
pom.xml

Prepare for m3 release

---

modules/samples/artifacts/PublishEventsToAmazonS3/AmazonS3SinkSample.siddhi
modules/samples/artifacts/PublishEventsToGooglCloudStorage/GCSSinkSample.siddhi

Add S3 sample and fix GCS sample

---

modules/distribution/pom.xml
modules/samples/sample-clients/kafka-avro-consumer/pom.xml
modules/samples/sample-clients/kafka-consumer/pom.xml
modules/samples/sample-clients/kafka-producer/pom.xml
modules/samples/sample-clients/mqtt-client/pom.xml
modules/samples/sample-clients/rabbitmq-producer/pom.xml
pom.xml

Bump dependency version

---

modules/distribution/pom.xml
pom.xml

Bump module versions of extensions

---

pom.xml

Bump siddhi-io-file version

---

pom.xml

Bump siddhi-io-prometheus version

---

modules/distribution/pom.xml
modules/distribution/src/assembly/bin.xml

> Download and add the latest in-place tool to pack

Add latest in-place tool to pack

---

modules/samples/artifacts/PublishKafkaInAvroFormat/PublishKafkaInCustomAvroFormat.siddhi

Fix PublishKafkaInCustomAvroFormat sample

---

modules/distribution/carbon-home/LICENSE.txt

Update license file

---

README.md

> $Title.
> Improving documentation.

Add security issues reporting guidelines

---

modules/samples/artifacts/PublishEventsToAmazonS3/AmazonS3FileSample.siddhi

> Add a sample to read events from a file and publish them to Amazon AWS S3.

Add AmazonS3FileSample

---

modules/samples/artifacts/PublishEventsToAmazonS3/AmazonS3FileSample.siddhi

> Add the minor changes done to the AmazonS3FileSample.

Modify AmazonS3FileSample

---

pom.xml

Upgrade new versions

---

modules/distribution/pom.xml
pom.xml

> $subject.
* Should add all extension information to `extensionDependencies.json`
* Should add documentation (for extension developers).
> Providing mechanism to install/uninstall dependencies related to Siddhi Extensions, in an automated manner.
> https://github.com/wso2/carbon-analytics/pull/1785

Add Siddhi Extensions Installer Backend

---

modules/distribution/carbon-home/conf/server/deployment.yaml
pom.xml

Update dependency versions

---

modules/samples/artifacts/ReceiveAndCount/ReceiveAndCount.siddhi

> Modify ReceiveAndCount
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

modify ReceiveAndCount

---

modules/samples/artifacts/IBMMessageQueueSample/IBMMessageQueue.siddhi
modules/samples/artifacts/PublishJmsInKeyvalueFormat/PublishJmsInKeyvalueFormat.siddhi
modules/samples/artifacts/PublishKafkaInJsonFormat/PublishKafkaInJsonFormat.siddhi

Alter samples to use Extension-Installer to install dependency jars

---

modules/samples/artifacts/PublishKafkaInBinaryFormat/PublishKafkaInBinaryFormat.siddhi
modules/samples/artifacts/ReceiveJMSInKeyvalueFormat/ReceiveJMSInKeyvalueFormat.siddhi
modules/samples/artifacts/ReceiveKafkaInBinaryFormat/ReceiveKafkaInBinaryFormat.siddhi
modules/samples/artifacts/SolrSample/Store-solr.siddhi
modules/samples/artifacts/TensorflowSample/TensorFlowTestApp.siddhi
pom.xml

$subject to accommodate Extension Installer

Update sample instructions

---

pom.xml

Bump key value map version

---

modules/samples/artifacts/CassandraSample/Store-cassandra.siddhi
modules/samples/artifacts/PublishJmsInXmlFormat/PublishJmsInXmlFormat.siddhi
modules/samples/artifacts/PublishPrometheusMetrics/PublishPrometheusMetricsHTTPServer.siddhi
modules/samples/artifacts/RDBMSSample/Store-rdbms.siddhi
modules/samples/artifacts/ReceiveJMSInJsonFormat/ReceiveJMSInJsonFormat.siddhi
modules/samples/artifacts/RedisSample/Store-redis.siddhi

Update samples Togo with Extension installer

---

modules/samples/artifacts/CSVMappingWithFile/CSVCustomMapping.siddhi

> Modify CSVCustomMapping.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Modify CSVCustomMapping

---

modules/distribution/pom.xml
pom.xml

Make the list of jars packed consistent with SI pack

---

pom.xml

Remove snapshot version of carbon-analytics dependency

---

modules/samples/artifacts/ReceiveEventsFromFile/ReceiveEventsFromFile.siddhi

Fix issue when showing sample related to file

Fix issue when showing sample related to file

---

pom.xml

Bump s3 and gcs versions

---

pom.xml

Upgrade carbon analytics version

---

pom.xml

Bump kafka version

---

pom.xml

Bump carbon and extension versions

---

modules/distribution/carbon-home/LICENSE.txt
pom.xml

Update License headers and bump carbon-analytics

---

modules/samples/artifacts/CDCSample/CDCWithListeningMode.siddhi

> $subject
> https://github.com/wso2/docs-ei/pull/2518

[Samples] Update instructions in 'CDCWithListeningMode' Siddhi app regarding enabling binlog in MySQL 8

---

pom.xml

Bump extension versions

---

pom.xml

Bump siddhi, carbon-analytics and extension versions

---

pom.xml

Bump carbon-analytics and extension versions

---

modules/distribution/src/assembly/filter.properties

add correct version for the product

Add correct version

---

modules/samples/sample-clients/http-client/build.xml
modules/samples/sample-clients/http-server/build.xml
modules/samples/sample-clients/kafka-avro-consumer/build.xml
modules/samples/sample-clients/kafka-consumer/build.xml
modules/samples/sample-clients/kafka-producer/build.xml

Add sample client dependency jar

Add dependency jar to kafka clients

---

pom.xml

> Prepare for 4.1.0-M2 release

Prepare for 4.1.0-M2 release

---

modules/distribution/src/assembly/filter.properties
pom.xml

Prepare for Alpha release

---

modules/samples/sample-clients/http-client/src/main/java/org/wso2/si/http/client/EventSendingUtil.java
modules/samples/sample-clients/http-client/src/main/java/org/wso2/si/http/client/HttpClient.java
modules/samples/sample-clients/http-server/src/main/java/org/wso2/si/http/server/HttpServerListener.java
modules/samples/sample-clients/http-server/src/main/java/org/wso2/si/http/server/HttpServerListenerHandler.java
modules/samples/sample-clients/http-server/src/main/java/org/wso2/si/http/server/HttpsServerListnerHandler.java
modules/samples/sample-clients/jms-consumer/src/main/java/org/wso2/si/sample/jms/consumer/JmsReceiver.java
modules/samples/sample-clients/jms-producer/src/main/java/org/wso2/si/sample/jms/client/JmsClient.java
modules/samples/sample-clients/kafka-avro-consumer/src/main/java/org/wso2/si/sample/kafka/avro/consumer/KafkaReceiver.java
modules/samples/sample-clients/kafka-consumer/src/main/java/org/wso2/si/sample/kafka/consumer/KafkaReceiver.java
modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/si/sample/kafka/client/EventSendingUtil.java
modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/si/sample/kafka/client/KafkaClient.java
modules/samples/sample-clients/mqtt-client/src/main/java/org/wso2/si/mqtt/client/EventSendingUtil.java
modules/samples/sample-clients/mqtt-client/src/main/java/org/wso2/si/mqtt/client/MqttClient.java
modules/samples/sample-clients/mqtt-consumer/src/main/java/org/wso2/si/sample/mqtt/consumer/MqttReceiver.java
modules/samples/sample-clients/prometheus-client/pom.xml
modules/samples/sample-clients/rabbitmq-consumer/src/main/java/org/wso2/si/sample/rabbitmq/consumer/RabbitMQReceiver.java
modules/samples/sample-clients/rabbitmq-producer/src/main/java/org/wso2/si/sample/rabbitmq/producer/EventSendingUtil.java
modules/samples/sample-clients/rabbitmq-producer/src/main/java/org/wso2/si/sample/rabbitmq/producer/RabbitMQProducer.java
modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/si/tcp/client/EventSendingUtil.java
modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/si/tcp/client/StoreTestClient.java
modules/samples/sample-clients/tcp-client/src/main/java/org/wso2/si/tcp/client/TCPClient.java
modules/samples/sample-clients/tcp-server/src/main/java/org/wso2/si/tcp/server/TCPServer.java
modules/samples/sample-clients/websocket-producer/src/main/java/org/wso2/si/sample/websocket/server/EventSendingUtil.java
modules/samples/sample-clients/websocket-producer/src/main/java/org/wso2/si/sample/websocket/server/WebSocketProducer.java
modules/samples/sample-clients/websocket-receiver/src/main/java/org/wso2/si/sample/websocket/receiver/WebSocketReceiver.java
pom.xml

Upgrade extension versions and remove log4j1 usages

Upgrade extension versions and remove log4j1 usages

---

modules/samples/sample-clients/http-server/src/main/java/org/wso2/si/http/server/HttpServerListener.java
modules/samples/sample-clients/http-server/src/main/java/org/wso2/si/http/server/HttpServerListenerHandler.java
modules/samples/sample-clients/http-server/src/main/java/org/wso2/si/http/server/HttpServerMain.java
modules/samples/sample-clients/http-server/src/main/java/org/wso2/si/http/server/HttpsServerListnerHandler.java
modules/samples/sample-clients/kafka-producer/src/main/java/org/wso2/si/sample/kafka/client/KafkaClient.java
modules/samples/sample-clients/tcp-server/src/main/java/org/wso2/si/tcp/server/TCPServer.java
pom.xml

> Prepare for the Beta release

Prepare for Beta release

---

modules/samples/sample-clients/http-server/build.xml
modules/samples/sample-clients/http-server/src/main/java/org/wso2/si/http/server/HttpServerMain.java

Fix http server sample

---

modules/distribution/carbon-home/LICENSE.txt
pom.xml

Bump rdbms version

---

modules/distribution/pom.xml
modules/samples/sample-clients/http-client/pom.xml
modules/samples/sample-clients/http-server/pom.xml
modules/samples/sample-clients/jms-consumer/pom.xml
modules/samples/sample-clients/jms-producer/pom.xml
modules/samples/sample-clients/kafka-avro-consumer/pom.xml
modules/samples/sample-clients/kafka-consumer/pom.xml
modules/samples/sample-clients/kafka-producer/pom.xml
modules/samples/sample-clients/mqtt-client/pom.xml
modules/samples/sample-clients/mqtt-consumer/pom.xml
modules/samples/sample-clients/pom.xml
modules/samples/sample-clients/prometheus-client/pom.xml
modules/samples/sample-clients/rabbitmq-consumer/pom.xml
modules/samples/sample-clients/rabbitmq-producer/pom.xml
modules/samples/sample-clients/tcp-client/pom.xml
modules/samples/sample-clients/tcp-server/pom.xml
modules/samples/sample-clients/websocket-producer/pom.xml
modules/samples/sample-clients/websocket-receiver/pom.xml
pom.xml

Update version to next 4.2.0 release

Update snapshot versions to 4.2.0

---

modules/samples/business-rules-templates/stock-exchange.json
modules/samples/business-rules-templates/sweet-factory .json
pom.xml

update dependencies for 4.2.0 m1 release

---

pom.xml

Update carbon coordinate dependency

---

pom.xml

Update coordinate version

---

pom.xml

> Update dependency version to the latest

Update kernel dependency

---

pom.xml

Update siddhi-execution-strings and sidddhi-io-file dependency versions.

Update execution.string and siddhi.file versions

---

modules/distribution/carbon-home/runtime/server/carbon.bat
modules/distribution/carbon-home/runtime/server/carbon.sh
modules/distribution/pom.xml
pom.xml

Add Java 11 support for the build
Fixes
https://github.com/wso2/api-manager/issues/1357

Add Java 11 support for build

---

modules/distribution/carbon-home/conf/osgi/launch.properties
modules/distribution/carbon-home/runtime/server/carbon.sh
pom.xml

Bump CDC and Json versions

---

modules/distribution/carbon-home/LICENSE.txt
modules/distribution/pom.xml
pom.xml

Bup dependency versions

---

pom.xml

Bump mime4j-core to 0.8.10.wso2v1 
public fix for issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5662

bump mime4j-core

---

.github/ISSUE_TEMPLATE/config.yml

Update new issue creation redirection

---

modules/distribution/pom.xml
pom.xml

Update dependencies for 4.3.0

---

modules/distribution/carbon-home/LICENSE.txt
pom.xml

Bump carbon analytics

---

README.md

Replace ei docs link with si docs
